# Read the Mean-SD tables generated by CW2 and name them:
# Notice that Parameter 4 was not used in the paper.

# Up and Yes refer to properties p_2 and p_3.
# Up is p_2 = 1, Yes is p_3 = 1.

CW.1 <- list("Param. 1, given All" = readRDS(here("MCS/MCS Tables/CW Mean-SD 1.rds")), "100%" = c(100) )
CW.2 <- list("Param. 2, given All" = readRDS(here("MCS/MCS Tables/CW Mean-SD 2.rds")), "100%" = c(100) )
CW.3 <- list("Param. 3, given All" = readRDS(here("MCS/MCS Tables/CW Mean-SD 3.rds")), "100%" = c(100) )
CW.4 <- list("Param. 4, given All" = readRDS(here("MCS/MCS Tables/CW Mean-SD 4.rds")), "100%" = c(100) )

CWup.1 <- list("Param. 1, given Up" = readRDS(here("MCS/MCS Tables/CW+Up Mean-SD 1.rds")), "100%" = c(100) )
CWup.2 <- list("Param. 2, given Up" = readRDS(here("MCS/MCS Tables/CW+Up Mean-SD 2.rds")), "100%" = c(100) )
CWup.3 <- list("Param. 3, given Up" = readRDS(here("MCS/MCS Tables/CW+Up Mean-SD 3.rds")), "100%" = c(100) )
CWup.4 <- list("Param. 4, given Up" = readRDS(here("MCS/MCS Tables/CW+Up Mean-SD 4.rds")), "100%" = c(100) )

CWyes.1 <- list("Param. 1, given Yes" = readRDS(here("MCS/MCS Tables/CW+Yes Mean-SD 1.rds")), "100%" = c(100) )
CWyes.2 <- list("Param. 2, given Yes" = readRDS(here("MCS/MCS Tables/CW+Yes Mean-SD 2.rds")), "100%" = c(100) )
CWyes.3 <- list("Param. 3, given Yes" = readRDS(here("MCS/MCS Tables/CW+Yes Mean-SD 3.rds")), "100%" = c(100) )
CWyes.4 <- list("Param. 4, given Yes" = readRDS(here("MCS/MCS Tables/CW+Yes Mean-SD 4.rds")), "100%" = c(100) )

CWupyes.1 <- list("Param. 1, given Up and Yes" = readRDS(here("MCS/MCS Tables/CW+Up+Yes Mean-SD 1.rds")), "100%" = c(100) )
CWupyes.2 <- list("Param. 2, given Up and Yes" = readRDS(here("MCS/MCS Tables/CW+Up+Yes Mean-SD 2.rds")), "100%" = c(100) )
CWupyes.3 <- list("Param. 3, given Up and Yes" = readRDS(here("MCS/MCS Tables/CW+Up+Yes Mean-SD 3.rds")), "100%" = c(100) )
CWupyes.4 <- list("Param. 4, given Up and Yes" = readRDS(here("MCS/MCS Tables/CW+Up+Yes Mean-SD 4.rds")), "100%" = c(100) )